# Generated by Django 2.2.6 on 2019-12-12 12:51

from django.db import migrations, models
import django.db.models.deletion
import my_cv.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceOrOutreach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=60)),
                ('duration', models.DurationField()),
                ('description', models.TextField()),
                ('is_outreach', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Experience/Outreach',
                'verbose_name_plural': 'Experience/Outreach',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=60)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=60)),
                ('duration', models.DurationField()),
                ('description', models.TextField()),
                ('university_url', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('skills', models.TextField()),
                ('interests', models.TextField()),
                ('resume', models.FileField(upload_to=my_cv.models.user_directory_path)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_cv.University')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_cv.ExperienceOrOutreach')),
                ('personal_links', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_cv.Link')),
            ],
            options={
                'verbose_name_plural': 'Resumes',
            },
        ),
    ]
