# Generated by Django 2.2.6 on 2019-12-14 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_cv', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Link',
            new_name='PersonalLink',
        ),
    ]
