# Generated by Django 2.2.6 on 2019-12-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cv', '0003_auto_20191214_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienceoroutreach',
            name='opportunity_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='experienceoroutreach',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='experienceoroutreach',
            name='opportunity_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='experienceoroutreach',
            name='position_title',
            field=models.CharField(max_length=150),
        ),
    ]
