# Generated by Django 2.2.6 on 2019-12-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cv', '0004_auto_20191214_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='duration',
        ),
        migrations.AddField(
            model_name='university',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='start_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
