# Generated by Django 2.2.6 on 2019-12-29 22:42

from django.db import migrations, models
import django.db.models.deletion
import my_cv.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cv', '0005_auto_20191229_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='my_cv.University'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='my_cv.ExperienceOrOutreach'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='interests',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='personal_links',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='my_cv.PersonalLink'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume',
            field=models.FileField(blank=True, upload_to=my_cv.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
