# Generated by Django 2.2.6 on 2020-01-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cv', '0006_auto_20191229_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_current_resume',
            field=models.BooleanField(default=False),
        ),
    ]
