# Generated by Django 2.2.6 on 2020-01-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cv', '0008_auto_20200110_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name_plural': 'Education'},
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume',
            field=models.FileField(blank=True, upload_to='resumes/'),
        ),
    ]
