# Generated by Django 2.2.6 on 2020-01-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cv', '0009_auto_20200110_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume_name',
            field=models.CharField(max_length=100),
        ),
    ]
