# Generated by Django 2.2.6 on 2020-01-15 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_cv', '0011_auto_20200110_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['name'], 'verbose_name_plural': 'Education'},
        ),
        migrations.AlterModelOptions(
            name='experienceoroutreach',
            options={'ordering': ['opportunity_name'], 'verbose_name': 'Experience/Outreach', 'verbose_name_plural': 'Experience/Outreach'},
        ),
        migrations.AlterModelOptions(
            name='personallink',
            options={'ordering': ['site_name']},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-is_current_resume'], 'verbose_name_plural': 'Resumes'},
        ),
    ]
