# Generated by Django 2.2.6 on 2020-01-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cv', '0012_auto_20200115_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
