# Generated by Django 2.2.6 on 2020-01-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cv', '0013_education_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienceoroutreach',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
