# Generated by Django 2.2.6 on 2020-01-18 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_cv', '0014_experienceoroutreach_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experienceoroutreach',
            options={'ordering': ['name'], 'verbose_name': 'Experience/Outreach', 'verbose_name_plural': 'Experience/Outreach'},
        ),
        migrations.RenameField(
            model_name='experienceoroutreach',
            old_name='opportunity_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='experienceoroutreach',
            old_name='opportunity_url',
            new_name='url',
        ),
    ]
