# Generated by Django 2.2.6 on 2020-01-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cv', '0015_auto_20200118_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
