# Generated by Django 2.2.6 on 2020-01-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cv', '0016_resume_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-is_current_resume', '-last_edited'], 'verbose_name_plural': 'Resumes'},
        ),
        migrations.AddField(
            model_name='resume',
            name='include_in_context',
            field=models.BooleanField(default=False),
        ),
    ]
