# Generated by Django 2.2.6 on 2020-01-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cv', '0018_auto_20200124_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='date_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.ManyToManyField(blank=True, to='my_cv.Education'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.ManyToManyField(blank=True, to='my_cv.ExperienceOrOutreach'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='interests',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='is_current_resume',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resume',
            name='last_edited',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='resume',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='personal_links',
            field=models.ManyToManyField(blank=True, to='my_cv.PersonalLink'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume',
            field=models.FileField(blank=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
