# Generated by Django 2.2.6 on 2020-02-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cv', '0019_auto_20200124_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
