# Generated by Django 2.2.11 on 2020-03-07 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_cv', '0020_resume_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experienceoroutreach',
            options={'ordering': ['-end_date', 'name'], 'verbose_name': 'Experience/Outreach', 'verbose_name_plural': 'Experience/Outreach'},
        ),
    ]
