# Generated by Django 2.1.3 on 2018-11-17 14:19

from django.db import migrations, models


def generate_slugs(apps, schema_editor):
    # Post = apps.get_model('blog', 'Post')
    Post = apps.get_model("blog", "Post")
    db_alias = schema_editor.connection.alias

    print(Post.objects.all())

    for post in Post.objects.using(db_alias).all():
        post.slug = post.title + '/' + str(post.id)
        # post.alter_field()
class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=None, max_length=100, unique=False),
            preserve_default=False,
        ),
        # migrations.RunPython(generate_slugs),
        # migrations.AlterField(
        #     model_name='post',
        #     name='slug',
        #     field=models.SlugField(unique=True),
        #     preserve_default=False,
        # ),
    ]
