# Generated by Django 2.1.3 on 2019-03-09 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190114_1641'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
