# Generated by Django 2.1.3 on 2019-01-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('pushed_at', models.DateTimeField()),
                ('url', models.URLField(max_length=400)),
            ],
        ),
    ]
