# Generated by Django 2.1.3 on 2019-01-19 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Repository',
            new_name='RepositoryTest',
        ),
    ]
