# Generated by Django 2.2.1 on 2019-10-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20190119_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='github_repo_id',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
