# Generated by Django 2.2.6 on 2019-11-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_repository_github_repo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='github_repo_id',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
