# Generated by Django 2.2.6 on 2020-01-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_aboutcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageBlurb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('last_edited', models.DateTimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='repository',
            options={'ordering': ['-pushed_at'], 'verbose_name_plural': 'Repositories'},
        ),
        migrations.AlterField(
            model_name='repository',
            name='repo_name',
            field=models.CharField(max_length=300, verbose_name='Repository'),
        ),
    ]
