# Generated by Django 2.2.11 on 2020-03-07 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20200116_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutcontent',
            options={'verbose_name_plural': 'About content'},
        ),
        migrations.AlterModelOptions(
            name='homepageblurb',
            options={'verbose_name_plural': 'Homepage blurb'},
        ),
    ]
